# Generated by Django 4.2.7 on 2023-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_key',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
