# Generated by Django 4.2.7 on 2023-11-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_student_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_key',
        ),
    ]
