# Generated by Django 4.2.7 on 2023-11-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_student_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
