# Generated by Django 4.2.7 on 2023-11-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
