# Generated by Django 5.0.2 on 2024-04-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_student',
            field=models.ForeignKey(default='default_user____________', on_delete=django.db.models.deletion.CASCADE, related_name='room_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_user',
            field=models.ForeignKey(default='default_user____________', on_delete=django.db.models.deletion.CASCADE, related_name='room_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
