# Generated by Django 5.0.2 on 2024-04-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
    ]
